client_config_backend: 'settings'
client_config:
  client_id: '522587876359-uk1c5d7bhaa3vkloi7pkgf8rnpc469hl.apps.googleusercontent.com'
  client_secret: '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'

save_credentials: True
save_credentials_backend: 'file'
save_credentials_file: 'credentials_module.json'

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
